# Generated by Django 5.2.17 on 2026-09-22 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('PROCUREMENT_OFFICER', 'Procurement Officer'), ('ADMIN', 'Admin')], default='EMPLOYEE', max_length=30),
        ),
    ]
